YEAR = 2011

REGIONS_ROOT = "census_2011", "administrative_boundaries", "Limiti_2011_WGS84", "Reg2011_WGS84", "Reg2011_WGS84.shp"
REGIONS_COLUMN = ['COD_REG', 'REGIONE']
REGIONS_COLUMN_REMAPPING = {'REGIONE': 'DEN_REG'}

PROVINCES_ROOT = "census_2011", "administrative_boundaries", "Limiti_2011_WGS84", "Prov2011_WGS84", "Prov2011_WGS84.shp"
PROVINCES_COLUMN = ['COD_PRO', 'PROVINCIA', 'SIGLA']
PROVINCES_COLUMN_REMAPPING = {'PROVINCIA': 'DEN_PROV'}

MUNICIPALITIES_ROOT = "census_2011", "administrative_boundaries", "Limiti_2011_WGS84", "Com2011_WGS84", "Com2011_WGS84.shp"
MUNICIPALITIES_COLUMN = ['PRO_COM', 'COMUNE', 'COD_REG', 'COD_PRO']
MUNICIPALITIES_COLUMN_REMAPPING = {'COD_PRO': 'COD_PROV'}
