import datetime
import logging
import os
from pathlib import Path
from typing import Any

import geopandas as gpd
import pandas as pd

from istatcelldata.config import census_data
from istatcelldata.logger_config import configure_logging

# Configure logging at the start of the script
configure_logging()
# Define the logger as a global variable
logger = logging.getLogger(__name__)


def finalize_census_data(
    census_data_path: Path,
    years: list,
    output_data_folder: Path | None = None,
    delete_preprocessed_data: bool = False,
):
    """Finalize census data by merging geodata and tabular data into a single GeoPackage.

    For each specified year, this function:
    1. Reads geographic data (census sections) from layer `census<year>`.
    2. Reads tabular data from layer `data<year>`.
    3. Removes unnecessary columns from tabular data.
    4. Performs a join between geographic and tabular data on key `SEZ<year>`.
    5. Sorts the data and builds a final GeoDataFrame.
    6. Saves the result to a GeoPackage named `census_data.gpkg`,
       with one layer per year (`census<year>`).

    Args:
        census_data_path: Folder containing the pre-processed GeoPackage file
            (`census.gpkg`), generated by previous workflow stages.
        years: List of census years to finalize (e.g., [1991, 2001, 2011, 2021]).
        output_data_folder: Optional folder where the final GeoPackage
            `census_data.gpkg` will be saved. If None, the file is saved in
            `census_data_path`.
        delete_preprocessed_data: If True, deletes the `census.gpkg` file after
            finalization is complete.

    Raises:
        FileNotFoundError: If the main GeoPackage file `census.gpkg` does not
            exist in the path specified by `census_data_path`.
        KeyError: If the join column `SEZ<year>` is not present in the geographic
            or tabular data, or if the columns to remove are not defined in
            `census_data[year]['data_columns_to_remove']`.

    Note:
        The join key between geographic and tabular data is dynamic and follows
        the `SEZ<year>` convention. Columns to remove from tabular data are
        defined in `census_data[year]['data_columns_to_remove']`. The final
        GeoPackage may contain multiple layers, one per processed year.
    """
    time_start = datetime.datetime.now()
    logging.info(f"Starting census preprocessing at {time_start} for years: {years}")

    # Path to the main GeoPackage file
    main_data = census_data_path.joinpath("census.gpkg")

    for year in years:
        logging.info(f"Starting census data finalization for year {year}")

        if not main_data.exists():
            error_message = f"Main GeoPackage file not found: {main_data}"
            logging.error(error_message)
            raise FileNotFoundError(error_message)

        logging.info(f"Loading geodata from layer 'census{year}'")
        geodata = gpd.read_file(filename=main_data, layer=f"census{year}")

        logging.info(f"Loading tabular data from layer 'data{year}'")
        data = gpd.read_file(filename=main_data, layer=f"data{year}")
        year_data: dict[str, Any] = census_data[year]  # type: ignore[assignment]
        columns_to_remove = year_data["data_columns_to_remove"]
        data.drop(columns=columns_to_remove, inplace=True)

        # Merge geodata with tabular data
        join_key = f"SEZ{year}"

        if join_key not in geodata.columns or join_key not in data.columns:
            error_message = (
                f"Join column '{join_key}' not found in geodata or tabular data"
            )
            logging.error(error_message)
            raise KeyError(error_message)

        logging.info(f"Merging data on column '{join_key}'")
        join_data = pd.merge(
            left=geodata,
            right=data,
            how="left",
            on=join_key,
        )
        join_data.fillna(value=0, inplace=True)

        # Remove "index" column and sort data
        if "index" in join_data.columns:
            join_data.drop(columns=["index"], inplace=True)
            logging.info("Column 'index' removed from data")

        join_data.sort_values(by=join_key, inplace=True)
        logging.info(f"Data sorted by column '{join_key}'")

        # Create final GeoDataFrame
        gdf = gpd.GeoDataFrame(data=join_data, geometry=geodata.geometry.name, crs=geodata.crs)

        # Define output file path
        filename = "census_data.gpkg"
        file_path = (
            output_data_folder.joinpath(filename)
            if output_data_folder
            else census_data_path.joinpath(filename)
        )

        # Save final file as GeoPackage
        logging.info(f"Saving final data to file {file_path}")
        gdf.to_file(filename=str(file_path), driver="GPKG", layer=f"census{year}")

    # Delete pre-processed data if requested
    if delete_preprocessed_data:
        logging.info(f"Deleting pre-processed file: {main_data}")
        os.remove(str(main_data))

    time_end = datetime.datetime.now()
    elapsed_time = time_end - time_start
    logging.info(f"Preprocessing completed in {elapsed_time}.")
